name: Generate sitemap

on:
  push:
    branches: [ master ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate sitemap

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 

    - name: Generate sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://www.jannick-wolters.de

    - name: Push sitemap
      continue-on-error: true
      run: |
        git config --global user.name "jawolters (GitHub Actions sitemap generator)"
        git config --global user.email "mail@jannick-wolters.de"
        git add sitemap.xml
        git commit -m "updated sitemap.xml (Github Actions)"
        git push